export const categories = [
  {
    name: "CCTV & Surveillance",
    slug: "cctv-surveillance",
    icon: "camera",
    description: "Security cameras and video surveillance products",
    subcategories: [
      "Bullet Cameras",
      "Dome Cameras",
      "Turret Cameras",
      "PTZ Cameras",
      "Speed Dome Cameras",
      "IP Cameras",
      "Analog Cameras",
      "Wi-Fi Cameras",
      "Outdoor Cameras",
      "Indoor Cameras",
      "Varifocal Cameras",
      "Motorized Cameras",
      "360° Cameras",
      "Fisheye Cameras",
      "Thermal Cameras",
      "ANPR Cameras",
      "LPR Cameras",
      "Color Night Vision Cameras",
      "Solar CCTV Cameras",
    ],
  },

  {
    name: "DVR / NVR & Recording",
    slug: "dvr-nvr-recording",
    icon: "hard-drive",
    description: "DVR, NVR and video recording equipment",
    subcategories: [
      "DVR",
      "XVR",
      "NVR",
      "PoE NVR",
      "AI NVR",
      "Hybrid NVR",
      "Video Management Server",
    ],
  },

  {
    name: "AI Cameras & Analytics",
    slug: "ai-cameras-analytics",
    icon: "brain",
    description: "AI-powered cameras and intelligent video analytics",
    subcategories: [
      "Human Detection Cameras",
      "Vehicle Detection Cameras",
      "Face Recognition Cameras",
      "Intrusion Detection Cameras",
      "Fire Detection Cameras",
      "Smoke Detection Cameras",
      "People Counting Cameras",
      "Crowd Detection Cameras",
      "License Plate Recognition",
      "ANPR Systems",
      "PPE Detection",
      "Line Crossing Detection",
      "Loitering Detection",
      "Object Detection",
      "Retail Analytics",
      "Traffic Analytics",
    ],
  },

  {
    name: "Storage & Hard Drives",
    slug: "storage-hard-drives",
    icon: "database",
    description: "Surveillance and enterprise storage solutions",
    subcategories: [
      "Surveillance HDD",
      "Enterprise HDD",
      "SSD",
      "NVMe SSD",
      "MicroSD Cards",
      "NAS Storage",
      "Network Storage",
      "RAID Storage",
      "Storage Servers",
    ],
  },

  {
    name: "Networking Products",
    slug: "networking-products",
    icon: "network",
    description: "Routers, switches, Wi-Fi and networking equipment",
    subcategories: [
      "Routers",
      "Network Switches",
      "PoE Switches",
      "Managed Switches",
      "Unmanaged Switches",
      "Enterprise Routers",
      "Wi-Fi Access Points",
      "Outdoor Wi-Fi",
      "Wi-Fi Mesh Systems",
      "Wireless Bridges",
      "Point-to-Point Wireless",
      "Network Controllers",
      "Fiber Networking",
      "Network Accessories",
    ],
  },

  {
    name: "Access Control",
    slug: "access-control",
    icon: "scan-face",
    description: "Biometric and electronic access control systems",
    subcategories: [
      "Fingerprint Attendance",
      "Face Recognition Attendance",
      "RFID Attendance",
      "Biometric Access Controllers",
      "RFID Readers",
      "RFID Cards",
      "RFID Key Fobs",
      "Door Controllers",
      "Magnetic Door Locks",
      "Electric Door Locks",
      "Smart Door Locks",
      "Exit Push Buttons",
      "Emergency Exit Buttons",
      "Door Sensors",
      "Visitor Management",
      "Flap Barriers",
      "Turnstiles",
      "Full Height Turnstiles",
      "Boom Barriers",
    ],
  },

  {
    name: "Video Door Phones",
    slug: "video-door-phones",
    icon: "door-open",
    description: "Video door phones, intercoms and smart doorbells",
    subcategories: [
      "Video Door Phones",
      "IP Video Door Phones",
      "Wi-Fi Video Door Phones",
      "Smart Video Doorbells",
      "Villa Video Door Phones",
      "Apartment Video Door Phones",
      "Indoor Monitors",
      "Outdoor Door Stations",
      "IP Intercoms",
      "Audio Intercoms",
      "GSM Intercoms",
      "SIP Intercoms",
    ],
  },

  {
    name: "Alarm & Safety Systems",
    slug: "alarm-safety-systems",
    icon: "shield-alert",
    description: "Security alarms and fire safety systems",
    subcategories: [
      "Burglar Alarm Systems",
      "Home Alarm Systems",
      "Office Alarm Systems",
      "Wireless Alarm Systems",
      "GSM Alarm Systems",
      "Wi-Fi Alarm Systems",
      "Alarm Control Panels",
      "PIR Motion Sensors",
      "Door Magnetic Sensors",
      "Glass Break Sensors",
      "Vibration Sensors",
      "Panic Buttons",
      "Alarm Sirens",
      "Strobe Sirens",
      "Fire Alarm Panels",
      "Addressable Fire Alarm",
      "Conventional Fire Alarm",
      "Smoke Detectors",
      "Heat Detectors",
      "Flame Detectors",
      "Manual Call Points",
    ],
  },

  {
    name: "Smart Home & Automation",
    slug: "smart-home-automation",
    icon: "house",
    description: "Smart home devices and automation systems",
    subcategories: [
      "Smart Door Locks",
      "Smart Doorbells",
      "Smart Cameras",
      "Smart Switches",
      "Smart Plugs",
      "Smart Lights",
      "Smart Curtains",
      "Smart Motion Sensors",
      "Smart Door Sensors",
      "Smart Temperature Sensors",
      "Smart Home Hubs",
      "Automation Controllers",
      "Smart Energy Meters",
      "Smart Thermostats",
      "Smart Security Kits",
    ],
  },

  {
    name: "Audio Visual",
    slug: "audio-visual",
    icon: "speaker",
    description: "Professional audio and visual equipment",
    subcategories: [
      "PA Systems",
      "Power Amplifiers",
      "Digital Amplifiers",
      "Audio Mixers",
      "Digital Mixers",
      "Wireless Microphones",
      "Wired Microphones",
      "Ceiling Speakers",
      "Wall Mount Speakers",
      "Column Speakers",
      "Horn Speakers",
      "Subwoofers",
      "Soundbars",
      "Conference Speakers",
      "Audio Processors",
      "Equalizers",
    ],
  },

  {
    name: "Video Conferencing",
    slug: "video-conferencing",
    icon: "video",
    description: "Meeting room and video conferencing solutions",
    subcategories: [
      "USB Conference Cameras",
      "PTZ Conference Cameras",
      "Conference Camera Bars",
      "Conference Microphones",
      "Wireless Conference Microphones",
      "Conference Speakers",
      "Video Conference Systems",
      "Meeting Room Systems",
      "Conference Controllers",
      "Wireless Presentation Systems",
      "All-in-One Video Bars",
    ],
  },

  {
    name: "LED Displays & Digital Signage",
    slug: "led-displays-signage",
    icon: "monitor",
    description: "LED displays, digital signage and commercial displays",
    subcategories: [
      "Indoor LED Displays",
      "Outdoor LED Displays",
      "LED Video Walls",
      "Fine Pixel LED Displays",
      "Digital Signage Displays",
      "Commercial Displays",
      "Interactive Displays",
      "Touch Displays",
      "Advertising Displays",
      "Digital Kiosks",
      "Digital Signage Players",
      "LED Video Processors",
      "LED Controllers",
    ],
  },

  {
    name: "Servers & Data Center",
    slug: "servers-data-center",
    icon: "server",
    description: "Enterprise servers and data center equipment",
    subcategories: [
      "Tower Servers",
      "Rack Servers",
      "Blade Servers",
      "GPU Servers",
      "AI Servers",
      "Storage Servers",
      "Backup Servers",
      "Database Servers",
      "Application Servers",
      "NAS Servers",
      "Server Racks",
      "Network Racks",
      "KVM Switches",
      "Rack PDUs",
      "Server Rail Kits",
      "Server Cooling Systems",
    ],
  },

  {
    name: "Computers & Laptops",
    slug: "computers-laptops",
    icon: "laptop",
    description: "Computers, laptops and computer accessories",
    subcategories: [
      "Business Desktops",
      "Office Desktops",
      "Mini PCs",
      "All-in-One PCs",
      "Workstations",
      "Gaming PCs",
      "Business Laptops",
      "Professional Laptops",
      "Gaming Laptops",
      "Engineering Laptops",
      "AI Laptops",
      "Computer Monitors",
      "Keyboards",
      "Mouse",
      "Webcams",
      "Headsets",
      "Computer Speakers",
      "Laptop Docks",
      "USB Hubs",
      "Laptop Stands",
      "Laptop Bags",
    ],
  },

  {
    name: "UPS & Power Solutions",
    slug: "ups-power-solutions",
    icon: "battery-charging",
    description: "UPS, batteries and power protection equipment",
    subcategories: [
      "600VA UPS",
      "1KVA UPS",
      "2KVA UPS",
      "3KVA UPS",
      "5KVA UPS",
      "10KVA UPS",
      "20KVA UPS",
      "30KVA UPS",
      "Online UPS",
      "Offline UPS",
      "Line Interactive UPS",
      "Rack UPS",
      "Server UPS",
      "UPS Batteries",
      "Battery Banks",
      "Inverters",
      "Voltage Stabilizers",
      "Surge Protectors",
      "Power Distribution Units",
    ],
  },

  {
    name: "Drones & Accessories",
    slug: "drones-accessories",
    icon: "drone",
    description: "Professional, industrial and agricultural drones",
    subcategories: [
      "Camera Drones",
      "Surveillance Drones",
      "Enterprise Drones",
      "Industrial Drones",
      "Agriculture Drones",
      "Mapping Drones",
      "Inspection Drones",
      "Thermal Imaging Drones",
      "Drone Batteries",
      "Drone Chargers",
      "Drone Propellers",
      "Drone Controllers",
      "Drone Carrying Cases",
      "Drone Landing Pads",
      "Drone Cameras & Gimbals",
      "Drone Spare Parts",
    ],
  },

  {
    name: "Smart Agriculture",
    slug: "smart-agriculture",
    icon: "sprout",
    description: "Smart farming, IoT and agricultural monitoring",
    subcategories: [
      "Agriculture Drones",
      "Crop Monitoring Cameras",
      "Solar Farm Cameras",
      "Soil Moisture Sensors",
      "Soil Temperature Sensors",
      "Humidity Sensors",
      "Weather Stations",
      "Water Level Sensors",
      "Smart Irrigation Controllers",
      "Smart Irrigation Systems",
      "Farm IoT Gateways",
      "Livestock Monitoring",
      "AI Crop Monitoring",
      "Smart Farm Monitoring Kits",
    ],
  },

  {
    name: "Cloud & Software",
    slug: "cloud-software",
    icon: "cloud",
    description: "Cloud services and intelligent software solutions",
    subcategories: [
      "Cloud CCTV",
      "Cloud Storage",
      "Cloud NVR",
      "Remote CCTV Monitoring",
      "Cloud Access Control",
      "Cloud Attendance",
      "Remote Device Management",
      "Cloud Backup",
      "Network Monitoring Software",
      "Video Management Software",
      "AI Video Analytics Software",
    ],
  },

  {
    name: "Cabling & Accessories",
    slug: "cabling-accessories",
    icon: "cable",
    description: "Network, CCTV, fiber and installation accessories",
    subcategories: [
      "CAT5e Network Cable",
      "CAT6 Network Cable",
      "CAT6A Network Cable",
      "CAT7 Network Cable",
      "Fiber Optic Cable",
      "Single Mode Fiber",
      "Multi Mode Fiber",
      "HDMI Cables",
      "VGA Cables",
      "USB Cables",
      "CCTV Coaxial Cables",
      "Patch Cords",
      "RJ45 Connectors",
      "BNC Connectors",
      "DC Connectors",
      "Fiber Connectors",
      "Patch Panels",
      "Keystone Jacks",
      "Cable Managers",
      "Cable Trays",
      "Junction Boxes",
      "Camera Mounts",
      "Wall Mounts",
      "Ceiling Mounts",
      "Rack Cabinets",
    ],
  },

  {
    name: "Tools & Testers",
    slug: "tools-testers",
    icon: "wrench",
    description: "Professional IT and installation tools",
    subcategories: [
      "LAN Cable Testers",
      "Network Cable Testers",
      "CCTV Testers",
      "PoE Testers",
      "Fiber Testers",
      "Fiber Cleavers",
      "Crimping Tools",
      "RJ45 Crimping Tools",
      "Cable Strippers",
      "Cable Trackers",
      "Multimeters",
      "Network Tool Kits",
      "CCTV Installation Tool Kits",
    ],
  },

  {
    name: "Office Equipment",
    slug: "office-equipment",
    icon: "printer",
    description: "Printers, scanners and office equipment",
    subcategories: [
      "Laser Printers",
      "Inkjet Printers",
      "Multifunction Printers",
      "Barcode Printers",
      "Thermal Printers",
      "Receipt Printers",
      "Label Printers",
      "Document Scanners",
      "Barcode Scanners",
      "Photocopiers",
      "Paper Shredders",
      "Office Projectors",
    ],
  },

  {
    name: "POS & Retail Solutions",
    slug: "pos-retail-solutions",
    icon: "shopping-cart",
    description: "POS and retail technology solutions",
    subcategories: [
      "POS Machines",
      "POS Terminals",
      "Barcode Scanners",
      "QR Code Scanners",
      "Receipt Printers",
      "Cash Drawers",
      "Customer Displays",
      "Label Printers",
      "Retail CCTV Cameras",
      "People Counting Systems",
      "Retail Analytics",
      "Inventory Management Systems",
    ],
  },

  {
    name: "IoT Devices & Sensors",
    slug: "iot-devices-sensors",
    icon: "cpu",
    description: "IoT devices, sensors and smart monitoring equipment",
    subcategories: [
      "IoT Gateways",
      "Temperature Sensors",
      "Humidity Sensors",
      "Motion Sensors",
      "Door Sensors",
      "Water Leak Sensors",
      "Gas Sensors",
      "Smoke Sensors",
      "Light Sensors",
      "Energy Meters",
      "Smart Energy Monitors",
      "Industrial IoT Controllers",
      "IoT Monitoring Kits",
    ],
  },

  {
    name: "Vehicle & Parking Solutions",
    slug: "vehicle-parking-solutions",
    icon: "car",
    description: "Vehicle monitoring and parking management systems",
    subcategories: [
      "ANPR Cameras",
      "License Plate Cameras",
      "Parking Cameras",
      "Parking Sensors",
      "Parking Management Systems",
      "Parking Guidance Systems",
      "Vehicle Counting Systems",
      "Boom Barriers",
      "Automatic Gates",
      "RFID Vehicle Readers",
      "RFID Vehicle Tags",
      "Vehicle GPS Trackers",
      "Fleet Tracking Systems",
    ],
  },

  {
    name: "Solar & Backup Solutions",
    slug: "solar-backup-solutions",
    icon: "sun",
    description: "Solar-powered security and backup systems",
    subcategories: [
      "Solar CCTV Cameras",
      "Solar CCTV Kits",
      "Solar Panels",
      "Solar Batteries",
      "Solar Inverters",
      "Solar Charge Controllers",
      "Solar Street Lights",
      "Solar Wi-Fi Systems",
      "Solar Surveillance Kits",
      "Solar Farm Monitoring Kits",
    ],
  },

  {
    name: "Combo Packages",
    slug: "combo-packages",
    icon: "package",
    description: "Complete security and IT solution packages",
    subcategories: [
      "Home Security Combo",
      "Office Essential Combo",
      "Complete Security Combo",
      "Smart Office Combo",
      "Retail Security Combo",
      "School Security Combo",
      "Enterprise IT Combo",
      "Smart Agriculture Combo",
      "Small Business Security Combo",
      "Apartment Security Combo",
      "Villa Security Combo",
      "Shop Security Combo",
      "Warehouse Security Combo",
      "Industrial Security Combo",
    ],
  },

  {
    name: "AMC & Maintenance",
    slug: "amc-maintenance",
    icon: "settings",
    description: "Annual maintenance and technical support services",
    subcategories: [
      "CCTV AMC",
      "Networking AMC",
      "Server AMC",
      "Computer AMC",
      "Access Control AMC",
      "Biometric AMC",
      "Fire Alarm AMC",
      "Audio Visual AMC",
      "LED Display AMC",
      "Video Wall AMC",
      "Wi-Fi AMC",
      "Smart Home AMC",
      "Complete IT AMC",
      "Enterprise IT Support",
      "Preventive Maintenance",
      "Emergency Breakdown Support",
    ],
  },
];

export default categories;