platform :ios, '14.0'

target 'App' do
  capacitor_pods
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'
  pod 'GoogleMaps'
  pod 'Socket.IO-Client-Swift', '~> 16.0.1'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorNetwork', :path => '../../node_modules/@capacitor/network'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
end
