import { CheckCircle2, ClipboardList, MapPin, Wrench } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { useCommerce } from "../context/CommerceContext";
import { money, recommendationsFor } from "../lib/products";
import ProductCard from "../components/ProductCard";

export default function OrderTracking() {
  const { orders } = useCommerce();
  const [params] = useSearchParams();
  const order = orders.find((item) => item.id === params.get("order")) || orders[0];
  if (!order) return <main className="min-h-screen bg-slate-50 p-12 text-center"><ClipboardList className="mx-auto text-slate-300" size={48} /><h1 className="mt-4 text-2xl font-bold">No orders yet</h1><p className="mt-2 text-slate-600">Your placed orders will appear here.</p></main>;
  const hasInstallation = Boolean(order.installationSlot);
  const steps = ["Order placed", order.paymentMethod === "online" ? "Payment pending" : "Confirmed", "Packed", "Out for delivery", "Delivered"];
  const orderedIds = new Set(order.items.map((item) => item.productId));
  const suggestions = [...new Map(order.items.flatMap((item) => recommendationsFor(item.productId)).filter((product) => !orderedIds.has(product.id)).map((product) => [product.id, product])).values()].slice(0, 4);
  return <main className="min-h-screen bg-slate-50 py-8"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="rounded-2xl bg-[#071426] p-7 text-white"><p className="text-sm text-amber-300">Order {order.id}</p><h1 className="mt-2 text-3xl font-extrabold">{order.status}</h1><p className="mt-3 text-slate-300">Placed on {new Date(order.createdAt).toLocaleDateString("en-IN", { dateStyle: "long" })} · {money(order.total)}</p></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Delivery timeline</h2><div className="mt-7 space-y-6">{steps.map((step, index) => <div key={step} className="flex gap-4"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${index === 0 ? "bg-green-600 text-white" : "bg-slate-100 text-slate-400"}`}>{index === 0 ? <CheckCircle2 size={18} /> : index + 1}</span><div><p className="font-bold text-slate-900">{step}</p><p className="mt-1 text-sm text-slate-500">{index === 0 ? "We have received your order." : "You will receive an SMS/WhatsApp update."}</p></div></div>)}</div>{hasInstallation && <div className="mt-8 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="flex items-center gap-2 font-bold text-slate-900"><Wrench size={18} className="text-amber-600" /> Installation appointment requested</p><p className="mt-2 text-sm text-slate-600">{order.installationSlot}</p></div>}</section><aside className="h-fit rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Delivery details</h2><p className="mt-4 flex gap-2 text-sm text-slate-600"><MapPin size={18} className="shrink-0 text-amber-500" />{order.address.name}<br />{order.address.line1}, {order.address.city} – {order.address.pin}<br />{order.address.phone}</p><h3 className="mt-7 font-bold">Items</h3>{order.items.map((item) => <div key={item.productId} className="mt-3 flex items-center gap-3 text-sm"><img src={item.product.image} className="h-10 w-10 rounded bg-slate-50" /><span>{item.product.name} × {item.quantity}</span></div>)}</aside></div>{suggestions.length > 0 && <section className="mt-12"><p className="text-sm font-bold uppercase tracking-wide text-amber-600">Based on your order</p><h2 className="mt-1 text-2xl font-extrabold text-slate-900">Recommended essentials</h2><p className="mt-2 text-slate-600">Add the accessories and upgrades that work with your purchase.</p><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{suggestions.map((product) => <ProductCard key={product.id} product={product} />)}</div></section>}</div></main>;
}
