export const allCategories = [
  "CCTV & Surveillance",
  "DVR / NVR & Recording",
  "AI Cameras & Analytics",
  "Storage & Hard Drives",
  "Networking Products",
  "Access Control",
  "Video Door Phones",
  "Alarm & Safety Systems",
  "Smart Home & Automation",
  "Audio Visual",
  "Video Conferencing",
  "LED Displays & Digital Signage",
  "Servers & Data Center",
  "Computers & Laptops",
  "UPS & Power Solutions",
  "Drones & Accessories",
  "Smart Agriculture",
  "Cloud & Software",
  "Cabling & Accessories",
  "Tools & Testers",
  "Office Equipment",
  "POS & Retail Solutions",
  "IoT Devices & Sensors",
  "Vehicle & Parking Solutions",
  "Solar & Backup Solutions",
  "Combo Packages",
  "AMC & Maintenance",
];

export default allCategories;
