export const products = [
  {
    id: "dahua-4mp-ai-dome-camera",
    name: "Dahua 4MP AI Dome Camera",
    category: "CCTV & Security",
    brand: "Dahua",
    price: 4499,
    mrp: 6499,
    rating: 4.7,
    reviews: 1208,
    stock: 18,
    delivery: "Delivery by tomorrow",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786165545/Dahua_4MP_AI_Dome_Camera_aqg3co.png",
    description: "AI-enabled dome camera with smart dual-light, human detection and IP67 protection.",
    features: ["4MP resolution", "AI human detection", "IP67 weatherproof", "Built-in microphone"],
    installationEligible: true,
  },
  {
    id: "tp-link-archer-ax55-router",
    name: "TP-Link Archer AX55 Wi-Fi 6 Router",
    category: "Networking",
    brand: "TP-Link",
    price: 5499,
    mrp: 7999,
    rating: 4.5,
    reviews: 634,
    stock: 32,
    delivery: "Delivery in 1–2 days",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786165545/tp-link-archer-ax55-router_ukrazq.webp",
    description: "Fast dual-band Wi-Fi 6 router for dependable home and business connectivity.",
    features: ["Wi-Fi 6", "Dual-band", "Gigabit ports", "WPA3 security"],
    installationEligible: true,
  },
  {
    id: "seagate-1tb-portable-hdd",
    name: "Seagate 1TB Portable Hard Drive",
    category: "Storage",
    brand: "Seagate",
    price: 4199,
    mrp: 5999,
    rating: 4.6,
    reviews: 874,
    stock: 45,
    delivery: "Delivery by tomorrow",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786017607/Synology_NAS_uhhbsb.webp",
    description: "Compact USB 3.0 portable storage for backups, CCTV recordings and everyday files.",
    features: ["1TB capacity", "USB 3.0", "Portable design", "Data recovery support"],
    installationEligible: false,
  },
  {
    id: "hikvision-8-channel-nvr",
    name: "Hikvision 8 Channel NVR",
    category: "CCTV & Security",
    brand: "Hikvision",
    price: 8999,
    mrp: 11999,
    rating: 4.4,
    reviews: 321,
    stock: 12,
    delivery: "Delivery in 2–3 days",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786165524/hikvision-8-channel-nvr_ds7yjg.jpg",
    description: "Reliable 8-channel network video recorder with remote viewing and storage expansion.",
    features: ["8 IP channels", "Remote viewing", "H.265+ compression", "HDMI output"],
    installationEligible: true,
  },
  {
    id: "dji-mini-4k-drone",
    name: "DJI Mini 4K Drone",
    category: "Drones & Cameras",
    brand: "DJI",
    price: 29999,
    mrp: 34999,
    rating: 4.8,
    reviews: 202,
    stock: 6,
    delivery: "Delivery in 2–4 days",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786165524/dji-mini-4k-drone_z66drz.jpg",
    description: "Lightweight 4K drone for professional inspection, surveying and content capture.",
    features: ["4K video", "31-minute flight time", "GPS return-to-home", "QuickShot modes"],
    installationEligible: false,
  },
  {
    id: "epson-ecotank-printer",
    name: "Epson EcoTank Wireless Printer",
    category: "Office Equipment",
    brand: "Epson",
    price: 15499,
    mrp: 18999,
    rating: 4.3,
    reviews: 442,
    stock: 14,
    delivery: "Delivery in 2–3 days",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786165523/epson-ecotank-printer_tyyuit.jpg",
    description: "Low-cost wireless all-in-one printer for offices and high-volume printing needs.",
    features: ["Wi-Fi printing", "Refillable ink tank", "Print, scan, copy", "Mobile app support"],
    installationEligible: true,
  },
  { id: "dell-inspiron-15-laptop", name: "Dell Inspiron 15 Laptop", category: "Computers & Laptops", brand: "Dell", price: 54990, mrp: 62990, rating: 4.5, reviews: 769, stock: 9, delivery: "Delivery in 2–3 days", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166603/dell-inspiron-15-laptop_yfutkj.jpg", description: "15-inch everyday performance laptop for work, study and office productivity.", features: ["Intel Core i5", "16GB RAM", "512GB SSD", "Windows 11"], installationEligible: true },
  { id: "logitech-m185-mouse", name: "Logitech M185 Wireless Mouse", category: "IT Accessories", brand: "Logitech", price: 899, mrp: 1195, rating: 4.4, reviews: 2092, stock: 88, delivery: "Delivery by tomorrow", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166597/logitech-m185-mouse_wwzxjh.jpg", description: "Reliable plug-and-play wireless mouse for office and laptop use.", features: ["2.4GHz wireless", "12-month battery", "Compact design", "USB receiver"], installationEligible: false },
  { id: "laptop-backpack", name: "Laptop Backpack 15.6 inch", category: "IT Accessories", brand: "Honey Vision", price: 1199, mrp: 1799, rating: 4.3, reviews: 485, stock: 53, delivery: "Delivery by tomorrow", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166597/laptop-backpack_dpeuvg.webp", description: "Water-resistant laptop backpack with cushioned compartment and organiser pockets.", features: ["15.6-inch fit", "Water-resistant", "Padded sleeve", "Accessory pockets"], installationEligible: false },
  { id: "tp-link-8-port-switch", name: "TP-Link 8 Port Gigabit Switch", category: "Networking", brand: "TP-Link", price: 2299, mrp: 3299, rating: 4.6, reviews: 934, stock: 27, delivery: "Delivery by tomorrow", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166596/tp-link-8-port-switch_nc5tmd.webp", description: "Unmanaged gigabit switch for expanding a dependable wired network.", features: ["8 gigabit ports", "Plug and play", "Fanless", "Energy efficient"], installationEligible: true },
  { id: "cat6-cable-100m", name: "CAT6 LAN Cable 100m", category: "Networking", brand: "Honey Vision", price: 2899, mrp: 3699, rating: 4.4, reviews: 254, stock: 35, delivery: "Delivery in 1–2 days", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166596/cat6-cable-100m_pl7qjz.webp", description: "High-quality CAT6 cable for structured networking and CCTV installations.", features: ["100 metre roll", "Copper conductor", "Gigabit-ready", "CCTV compatible"], installationEligible: true },
  { id: "apc-ups-1100va", name: "APC 1100VA UPS", category: "Power Backup", brand: "APC", price: 6999, mrp: 8499, rating: 4.5, reviews: 621, stock: 19, delivery: "Delivery in 2–3 days", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166595/apc-ups-1100va_h38kna.webp", description: "Reliable power backup for desktops, routers and surveillance systems.", features: ["1100VA backup", "Automatic voltage regulation", "Surge protection", "USB monitoring"], installationEligible: false },
  { id: "wd-purple-2tb-hdd", name: "WD Purple 2TB Surveillance HDD", category: "Storage", brand: "Western Digital", price: 5999, mrp: 7299, rating: 4.7, reviews: 487, stock: 21, delivery: "Delivery in 1–2 days", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166594/wd-purple-2tb-hdd_ikjvuu.webp", description: "Surveillance-grade storage designed for continuous CCTV recording.", features: ["2TB capacity", "24/7 workload", "Surveillance-grade", "3-year warranty"], installationEligible: true },
  { id: "cctv-power-supply", name: "CCTV 8 Channel Power Supply", category: "CCTV & Security", brand: "Honey Vision", price: 1199, mrp: 1599, rating: 4.2, reviews: 142, stock: 46, delivery: "Delivery by tomorrow", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166594/cctv-power-supply_byuurf.jpg", description: "Centralised power supply for up to eight CCTV camera installations.", features: ["8 channel output", "Short-circuit protection", "Metal cabinet", "Easy installation"], installationEligible: true },
  { id: "hikvision-video-doorbell", name: "Hikvision Smart Video Doorbell", category: "CCTV & Security", brand: "Hikvision", price: 6499, mrp: 8499, rating: 4.4, reviews: 186, stock: 11, delivery: "Delivery in 2–3 days", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166593/hikvision-video-doorbell_d3e1hd.jpg", description: "Smart doorbell with two-way communication and mobile alerts.", features: ["Two-way audio", "Mobile alerts", "Night vision", "Cloud-ready"], installationEligible: true },
  { id: "crucial-16gb-ram", name: "Crucial 16GB DDR4 RAM", category: "Components", brand: "Crucial", price: 3699, mrp: 4799, rating: 4.6, reviews: 753, stock: 39, delivery: "Delivery by tomorrow", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166592/crucial-16gb-ram_ulvkwv.webp", description: "16GB DDR4 memory upgrade for compatible desktop and laptop systems.", features: ["16GB capacity", "DDR4", "Easy upgrade", "Limited lifetime warranty"], installationEligible: true },
  { id: "hdmi-cable-2m", name: "Premium HDMI Cable 2m", category: "Cables & Connectors", brand: "Honey Vision", price: 499, mrp: 799, rating: 4.3, reviews: 566, stock: 101, delivery: "Delivery by tomorrow", image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786166592/hdmi-cable-2m_kcmife.webp", description: "High-speed HDMI cable for monitors, NVRs, TVs and projectors.", features: ["2 metre length", "4K-ready", "Gold-plated contacts", "Durable jacket"], installationEligible: false },
  {
    id: "face-recognition-terminal",
    name: "Smart Face Recognition Terminal",
    category: "Biometric & Access Control",
    brand: "Honey Vision",
    price: 15999,
    mrp: 19999,
    rating: 4.8,
    reviews: 302,
    stock: 10,
    delivery: "Delivery in 2–3 days",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786010027/cctv_y2raii.jpg",
    description: "Secure entry control terminal for offices, apartments and gated facilities.",
    features: ["Face capture", "Access control", "Attendance logging", "Cloud-ready"],
    installationEligible: true,
  },
  {
    id: "smart-door-lock",
    name: "Smart Door Lock Pro",
    category: "Biometric & Access Control",
    brand: "Honey Vision",
    price: 8999,
    mrp: 11999,
    rating: 4.6,
    reviews: 274,
    stock: 24,
    delivery: "Delivery by tomorrow",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786012476/headphone_ami4sj.webp",
    description: "Bluetooth and app-controlled smart lock with keypad and encrypted security access.",
    features: ["App unlock", "Keypad", "Auto-lock", "Door status alerts"],
    installationEligible: true,
  },
  {
    id: "fire-alarm-panel",
    name: "Addressable Fire Alarm Panel",
    category: "Security & Surveillance",
    brand: "Honey Vision",
    price: 21999,
    mrp: 26999,
    rating: 4.7,
    reviews: 188,
    stock: 8,
    delivery: "Delivery in 3–4 days",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786010026/power_bank_kqypks.jpg",
    description: "Reliable smoke and heat detection solution for commercial and industrial spaces.",
    features: ["Addressable detection", "Alarm integration", "System monitoring", "Remote alerts"],
    installationEligible: true,
  },
  {
    id: "wireless-motion-sensor",
    name: "Wireless Motion Sensor",
    category: "Security & Surveillance",
    brand: "Honey Vision",
    price: 2799,
    mrp: 3499,
    rating: 4.5,
    reviews: 215,
    stock: 56,
    delivery: "Delivery by tomorrow",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786010023/assesories_eizhmq.jpg",
    description: "Smart indoor motion sensor for theft detection, automation and alerts.",
    features: ["Wireless", "Low battery alert", "Automation trigger", "Smart app pairing"],
    installationEligible: false,
  },
  {
    id: "ultra-wide-monitor",
    name: "27-inch UltraWide Monitor",
    category: "Computers & Laptops",
    brand: "Dell",
    price: 23999,
    mrp: 28999,
    rating: 4.4,
    reviews: 395,
    stock: 14,
    delivery: "Delivery in 2–3 days",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786010024/display_rar3xa.webp",
    description: "Wide-screen productivity monitor for workstations, design tasks and multitasking.",
    features: ["27-inch display", "UltraWide", "HDMI + DisplayPort", "Eye-care"],
    installationEligible: false,
  },
  {
    id: "wifi-6-access-point",
    name: "Wi-Fi 6 Access Point",
    category: "Networking",
    brand: "TP-Link",
    price: 7999,
    mrp: 9999,
    rating: 4.7,
    reviews: 311,
    stock: 18,
    delivery: "Delivery in 1–2 days",
    image: "https://res.cloudinary.com/vhrkwyzs/image/upload/v1786010023/networking_ozm2kk.jpg",
    description: "Enterprise-grade wireless access point for large homes and office spaces.",
    features: ["Wi-Fi 6", "High coverage", "PoE support", "Mesh-ready"],
    installationEligible: true,
  },
];

export const bundleByProductId = {
  "dahua-4mp-ai-dome-camera": { title: "Complete CCTV camera setup", saving: 450, productIds: ["hikvision-8-channel-nvr", "wd-purple-2tb-hdd", "cat6-cable-100m", "cctv-power-supply"] },
  "hikvision-8-channel-nvr": { title: "Build your surveillance system", saving: 700, productIds: ["dahua-4mp-ai-dome-camera", "wd-purple-2tb-hdd", "cat6-cable-100m", "cctv-power-supply"] },
  "tp-link-archer-ax55-router": { title: "Reliable home network bundle", saving: 250, productIds: ["tp-link-8-port-switch", "cat6-cable-100m", "apc-ups-1100va"] },
  "dell-inspiron-15-laptop": { title: "Work-from-anywhere bundle", saving: 300, productIds: ["logitech-m185-mouse", "laptop-backpack", "crucial-16gb-ram"] },
  "dji-mini-4k-drone": { title: "Field inspection bundle", saving: 200, productIds: ["seagate-1tb-portable-hdd", "laptop-backpack", "apc-ups-1100va"] },
};

export function recommendationsFor(productId, limit = 4) {
  const bundle = bundleByProductId[productId];
  const chosen = bundle?.productIds.map((id) => products.find((product) => product.id === id)).filter(Boolean) || [];
  const source = products.find((product) => product.id === productId);
  const related = products.filter((product) => product.id !== productId && product.category === source?.category && !chosen.some((item) => item.id === product.id));
  return [...chosen, ...related, ...products.filter((product) => product.id !== productId && !chosen.some((item) => item.id === product.id) && !related.some((item) => item.id === product.id))].slice(0, limit);
}

export const categories = [...new Set(products.map((product) => product.category))];

const categorySlugMap = {
  "all-products": null,
  "cctv-surveillance": "CCTV & Surveillance",
  "dvr-nvr-recording": "DVR / NVR & Recording",
  "ai-cameras-analytics": "AI Cameras & Analytics",
  "storage-hard-drives": "Storage & Hard Drives",
  "networking-products": "Networking Products",
  "access-control": "Access Control",
  "video-door-phones": "Video Door Phones",
  "alarm-safety-systems": "Alarm & Safety Systems",
  "smart-home-automation": "Smart Home & Automation",
  "audio-visual": "Audio Visual",
  "video-conferencing": "Video Conferencing",
  "led-displays-signage": "LED Displays & Digital Signage",
  "servers-data-center": "Servers & Data Center",
  "computers-laptops": "Computers & Laptops",
  "ups-power-solutions": "UPS & Power Solutions",
  "drones-accessories": "Drones & Accessories",
  "smart-agriculture": "Smart Agriculture",
  "cloud-software": "Cloud & Software",
  "cabling-accessories": "Cabling & Accessories",
  "tools-testers": "Tools & Testers",
  "office-equipment": "Office Equipment",
  "pos-retail-solutions": "POS & Retail Solutions",
  "iot-devices-sensors": "IoT Devices & Sensors",
  "vehicle-parking-solutions": "Vehicle & Parking Solutions",
  "solar-backup-solutions": "Solar & Backup Solutions",
  "combo-packages": "Combo Packages",
  "amc-maintenance": "AMC & Maintenance",
  "cctv-and-security": "CCTV & Surveillance",
  "bullet-camera": "CCTV & Surveillance",
  "dome-camera": "CCTV & Surveillance",
  "ip-camera": "CCTV & Surveillance",
  "ptz-camera": "CCTV & Surveillance",
  "wi-fi-camera": "CCTV & Surveillance",
  "solar-cctv": "CCTV & Surveillance",
  "video-doorbell": "CCTV & Surveillance",
  "cctv-accessories": "CCTV & Surveillance",
  "dvr-and-nvr": "DVR / NVR & Recording",
  "4-channel": "DVR / NVR & Recording",
  "8-channel": "DVR / NVR & Recording",
  "16-channel": "DVR / NVR & Recording",
  "32-channel": "DVR / NVR & Recording",
  "nvr": "DVR / NVR & Recording",
  "xvr": "DVR / NVR & Recording",
  "poe-nvr": "DVR / NVR & Recording",
  "computers-and-laptops": "Computers & Laptops",
  laptops: "Computers & Laptops",
  desktop: "Computers & Laptops",
  "gaming-pc": "Computers & Laptops",
  monitors: "Computers & Laptops",
  "computer-components": "Components",
  networking: "Networking Products",
  "wi-fi-router": "Networking Products",
  "network-switch": "Networking Products",
  "poe-switch": "Networking Products",
  "access-point": "Networking Products",
  "lan-cable": "Networking Products",
  "network-accessories": "Networking Products",
  storage: "Storage & Hard Drives",
  hdd: "Storage & Hard Drives",
  "surveillance-hdd": "Storage & Hard Drives",
  ssd: "Storage & Hard Drives",
  "nvme-ssd": "Storage & Hard Drives",
  "pen-drive": "Storage & Hard Drives",
  "memory-card": "Storage & Hard Drives",
  "external-hdd": "Storage & Hard Drives",
  "it-accessories": "IT Accessories",
  accessories: "IT Accessories",
  mouse: "IT Accessories",
  keyboard: "IT Accessories",
  webcam: "IT Accessories",
  headset: "IT Accessories",
  "laptop-stand": "IT Accessories",
  "laptop-bag": "IT Accessories",
  "usb-hub": "IT Accessories",
  "cables-and-connectors": "Cabling & Accessories",
  "hdmi-cable": "Cabling & Accessories",
  "usb-cable": "Cabling & Accessories",
  "lan-cable-connectors": "Cabling & Accessories",
  "cat6-cable": "Cabling & Accessories",
  "bnc-connector": "Cabling & Accessories",
  "power-cable": "Cabling & Accessories",
  "printers-and-office": "Office Equipment",
  printers: "Office Equipment",
  cartridges: "Office Equipment",
  toners: "Office Equipment",
  "barcode-scanner": "Office Equipment",
  projector: "Office Equipment",
  "power-backup": "UPS & Power Solutions",
  ups: "UPS & Power Solutions",
  inverter: "UPS & Power Solutions",
  battery: "UPS & Power Solutions",
  stabilizer: "UPS & Power Solutions",
  "extension-board": "UPS & Power Solutions",
  drones: "Drones & Accessories",
  "camera-drone": "Drones & Accessories",
  "4k-drone": "Drones & Accessories",
  "gps-drone": "Drones & Accessories",
  "mini-drone": "Drones & Accessories",
  "drone-accessories": "Drones & Accessories",
  "access-control": "Access Control",
  biometric: "Access Control",
  "face-recognition": "Access Control",
  rfid: "Access Control",
  "smart-lock": "Smart Home & Automation",
  "access-controller": "Access Control",
  "safety-and-detection": "Alarm & Safety Systems",
  "smoke-detector": "Alarm & Safety Systems",
  "fire-alarm": "Alarm & Safety Systems",
  "motion-sensor": "Alarm & Safety Systems",
  "door-sensor": "Alarm & Safety Systems",
  "security-alarm": "Alarm & Safety Systems",
  "installation-and-services": "AMC & Maintenance",
  "cctv-installation": "CCTV & Surveillance",
  "cctv-amc": "AMC & Maintenance",
  "cctv-maintenance": "AMC & Maintenance",
  "network-installation": "Networking Products",
  "it-support": "IT Accessories",
};

export const slugifyCategory = (category) =>
  category
    .toLowerCase()
    .replaceAll("&", "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

export const categoryFromSlug = (slug) => {
  if (!slug) return null;
  const directMatch = categorySlugMap[slug];
  if (directMatch) return directMatch;
  return categories.find((category) => slugifyCategory(category) === slug) || null;
};

export const matchesCategorySlug = (productCategory, slug) => {
  if (!slug || slug === "all-products") return true;
  const canonicalCategory = categoryFromSlug(slug);
  return Boolean(canonicalCategory && productCategory === canonicalCategory);
};

export const money = (value) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
